#Expyriment 0.9.0 (Python 3.6.5), .xpe-file, coding: cp1252
#date: Wed Apr 10 2019 17:08:46
#sha1: None
#modules: 
#display: size=(1920, 1080), window_mode=False, open_gl=2
#os: uname_result(system='Windows', node='DESKTOP-OVOASGR', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
3829,stderr,received,'Traceback (most recent call last):'
3830,stderr,received,'  File "scripts\\mttexp.py", line 226, in <module>'
3832,stderr,received,'    after_to_the_left = expyriment.stimuli.Picture("documents\\arrows.png", position = (0, 700))'
3833,stderr,received,'  File "C:\\Users\\annaw\\Anaconda3\\lib\\site-packages\\expyriment\\stimuli\\_picture.py", line 49, in __init__'
3839,stderr,received,'    unicode2byte(filename)))'
3840,stderr,received,"OSError: The picture file 'b'documents\\x07rrows.png'' does not exist"
