#Expyriment 0.9.0 (Python 3.6.5), .xpe-file, coding: cp1252
#date: Tue Apr 02 2019 17:00:15
#sha1: None
#modules: 
#display: size=(1920, 1080), window_mode=False, open_gl=2
#os: uname_result(system='Windows', node='DESKTOP-OVOASGR', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
Time,Type,Event,Value,Detail,Detail2
10874,design,log,
#design: #exp: Questionnaire
#design: block_cnt,block_id,trial_cnt,trial_id
10874,design,logged,
10874,Experiment,started
10876,Stimulus,presented,24
11380,Stimulus,presented,0
13418,Stimulus,presented,26
13443,Stimulus,presented,26
13468,Stimulus,presented,26
13476,Stimulus,presented,27
16225,Stimulus,presented,27
16682,Stimulus,presented,27
16852,Stimulus,presented,27
17138,Stimulus,presented,27
17548,TextInput,entered,b'1985'
17548,stderr,received,'Traceback (most recent call last):'
17550,stderr,received,'  File "scripts\\questionnaire.py", line 236, in <module>'
17552,stderr,received,'    if answerDate == get_factor("trueDate"):'
17553,stderr,received,"NameError: name 'get_factor' is not defined"
